name: Run Unit Tests

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v1
      with: "5.6.0"
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
